filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /logs/nginx/access.log
    tags: ["nginx"]
    fields:
      log_type: nginx
    fields_under_root: true

  - type: log
    enabled: true
    paths:
      - /logs/ssh/auth.log
    tags: ["ssh"]
    fields:
      log_type: ssh
    fields_under_root: true
    json.keys_under_root: true
    json.add_error_key: true

  - type: log
    enabled: true
    paths:
      - /logs/app/requests.log
    tags: ["app"]
    fields:
      log_type: app
    fields_under_root: true
    json.keys_under_root: true
    json.add_error_key: true

  - type: log
    enabled: true
    paths:
      - /logs/windows/events.log
    tags: ["windows"]
    fields:
      log_type: windows
    fields_under_root: true
    json.keys_under_root: true
    json.add_error_key: true

output.logstash:
  hosts: ["logstash:5044"]

logging.level: info
