input {
  beats {
    port => 5044
  }
}

filter {

  if [agent][type] == "filebeat" and "nginx" in [tags] {
    grok {
      match => {
        "message" => '%{IPORHOST:client_ip} - %{DATA:ident} \[%{HTTPDATE:log_timestamp}\] \"%{WORD:http_method} %{URIPATHPARAM:request_uri} HTTP/%{NUMBER:http_version}\" %{NUMBER:status:int} %{NUMBER:bytes_sent:int} \"%{DATA:referrer}\" \"%{DATA:user_agent}\"'
      }
      tag_on_failure => ["_grokparsefailure_nginx"]
    }
    geoip {
      source => "client_ip"
      target => "geoip"
    }
    date {
      match => ["log_timestamp", "dd/MMM/yyyy:HH:mm:ss Z"]
      target => "@timestamp"
    }
    mutate {
      convert => { "status" => "integer" }
      convert => { "bytes_sent" => "integer" }
    }
  }

  if [agent][type] == "filebeat" and "ssh" in [tags] {
    geoip {
      source => "source_ip"
      target => "geoip"
    }
  }

  if [agent][type] == "filebeat" and "app" in [tags] {
    mutate {
      convert => { "status_code" => "integer" }
      convert => { "latency_ms" => "integer" }
    }
  }

  if [agent][type] == "winlogbeat" {
    mutate {
      add_field => { "log_source" => "windows_security" }
    }
  }

}

output {
  if [agent][type] == "winlogbeat" {
    elasticsearch {
      hosts => ["http://elasticsearch:9200"]
      index => "lab-windows-%{+YYYY.MM.dd}"
    }
  } else if "nginx" in [tags] {
    elasticsearch {
      hosts => ["http://elasticsearch:9200"]
      index => "lab-nginx-%{+YYYY.MM.dd}"
    }
  } else if "ssh" in [tags] {
    elasticsearch {
      hosts => ["http://elasticsearch:9200"]
      index => "lab-ssh-%{+YYYY.MM.dd}"
    }
  } else if "app" in [tags] {
    elasticsearch {
      hosts => ["http://elasticsearch:9200"]
      index => "lab-app-%{+YYYY.MM.dd}"
    }
  } else if "windows" in [tags] {
    elasticsearch {
      hosts => ["http://elasticsearch:9200"]
      index => "lab-windows-%{+YYYY.MM.dd}"
    }
  } else {
    elasticsearch {
      hosts => ["http://elasticsearch:9200"]
      index => "lab-misc-%{+YYYY.MM.dd}"
    }
  }
}
