worker_processes 1;

events { worker_connections 1024; }

http {
    log_format ecs_json escape=json
      '{'
      '"@timestamp":"$time_iso8601",'
      '"event":{"kind":"event","category":["web"],"type":["access"]},'
      '"source":{"ip":"$remote_addr"},'
      '"http":{"request":{"method":"$request_method"},"version":"$server_protocol",'
      '"response":{"status_code":$status,"body":{"bytes":$body_bytes_sent}}},'
      '"url":{"original":"$request_uri","path":"$uri"},'
      '"user_agent":{"original":"$http_user_agent"}'
      '}';

    access_log /logs/nginx/access.log ecs_json;

    upstream app { server app:5000; }

    server {
        listen 80;
        server_name _;

        location = /health { proxy_pass http://app/api/health; }
        location /products { proxy_pass http://app/api/products; }
        location /cart { proxy_pass http://app/api/cart; }
        location /checkout { proxy_pass http://app/api/checkout; }
        location /login { proxy_pass http://app/api/login; }
        location /admin { proxy_pass http://app/api/admin; }
        location /error { proxy_pass http://app/api/error; }
        location /slow { proxy_pass http://app/api/slow; }
        location / { proxy_pass http://app; }
    }
}
