input {
  beats {
    port => 5044
    ssl_enabled => true
    ssl_certificate => "/usr/share/logstash/certs/stack.crt"
    ssl_key => "/usr/share/logstash/certs/stack.key"
  }
}

filter {
  mutate {
    add_field => {
      "[observer][product]" => "elastic-stack"
      "[observer][type]" => "siem-lab"
    }
  }

  if [event][dataset] == "lab.nginx" {
    mutate {
      add_field => {
        "[event][kind]" => "event"
        "[event][category]" => "web"
        "[event][type]" => "access"
      }
    }
    mutate {
      add_tag => ["source:nginx"]
    }
  }

  if [event][dataset] == "lab.application" {
    mutate { add_tag => ["source:application"] }
    if [http][response][status_code] {
      mutate { convert => { "[http][response][status_code]" => "integer" } }
    }
    if [event][duration] {
      mutate { convert => { "[event][duration]" => "integer" } }
    }
    mutate { add_field => { "[event][category]" => "web" } }
  }

  if [event][dataset] == "lab.ssh" {
    mutate { add_tag => ["source:ssh"] }
    mutate {
      add_field => {
        "[event][kind]" => "event"
        "[event][category]" => "authentication"
        "[event][type]" => "start"
        "[event][action]" => "ssh_login"
      }
    }
    if [source][ip] { geoip { source => "[source][ip]" target => "[source][geo]" } }
  }

  if [event][dataset] == "lab.windows" {
    mutate { add_tag => ["source:windows"] }
    mutate {
      add_field => {
        "[event][kind]" => "event"
        "[event][category]" => "authentication"
      }
    }
  }

  if [event][dataset] == "lab.detection" {
    mutate {
      add_tag => ["source:detection"]
      add_field => { "[event][kind]" => "alert" }
    }
  }

  if [event][original] {
    mutate { add_tag => ["parse_failure"] }
  }
}

output {
  if "source:detection" in [tags] {
    elasticsearch {
      hosts => ["https://elasticsearch:9200"]
      user => "logstash_writer"
      password => "${LOGSTASH_PASSWORD}"
      ssl_enabled => true
      ssl_certificate_authorities => ["/usr/share/logstash/certs/ca.crt"]
      index => "security-detections-%{+YYYY.MM.dd}"
    }
  } else if "source:nginx" in [tags] {
    elasticsearch {
      hosts => ["https://elasticsearch:9200"]
      user => "logstash_writer"
      password => "${LOGSTASH_PASSWORD}"
      ssl_enabled => true
      ssl_certificate_authorities => ["/usr/share/logstash/certs/ca.crt"]
      index => "logs-nginx-%{+YYYY.MM.dd}"
    }
  } else if "source:ssh" in [tags] {
    elasticsearch {
      hosts => ["https://elasticsearch:9200"]
      user => "logstash_writer"
      password => "${LOGSTASH_PASSWORD}"
      ssl_enabled => true
      ssl_certificate_authorities => ["/usr/share/logstash/certs/ca.crt"]
      index => "logs-ssh-%{+YYYY.MM.dd}"
    }
  } else if "source:windows" in [tags] {
    elasticsearch {
      hosts => ["https://elasticsearch:9200"]
      user => "logstash_writer"
      password => "${LOGSTASH_PASSWORD}"
      ssl_enabled => true
      ssl_certificate_authorities => ["/usr/share/logstash/certs/ca.crt"]
      index => "logs-windows-%{+YYYY.MM.dd}"
    }
  } else if "source:application" in [tags] {
    elasticsearch {
      hosts => ["https://elasticsearch:9200"]
      user => "logstash_writer"
      password => "${LOGSTASH_PASSWORD}"
      ssl_enabled => true
      ssl_certificate_authorities => ["/usr/share/logstash/certs/ca.crt"]
      index => "logs-application-%{+YYYY.MM.dd}"
    }
  } else {
    elasticsearch {
      hosts => ["https://elasticsearch:9200"]
      user => "logstash_writer"
      password => "${LOGSTASH_PASSWORD}"
      ssl_enabled => true
      ssl_certificate_authorities => ["/usr/share/logstash/certs/ca.crt"]
      index => "logs-misc-%{+YYYY.MM.dd}"
    }
  }
}
